// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/es/messages.json"
    | "/_locales/hi/messages.json"
    | "/_locales/ru/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/48.png"
    | "/icon/icon.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
